Python NumPy Exercise Exercise 
Exercise 1: Create a 4X2 integer array and Prints its attributes
Note: The element must be a type of unsigned int16. And print the following Attributes: – 
The shape of an array. 
 Array dimensions. 
 The Length of each element of the array in bytes.

In [3]:
import numpy as np

firstArray = np.empty([4,2], dtype = np.uint16) 
print("Printing Array")
print(firstArray)

print("Numpy Attributes")
print("Shape is: ", firstArray.shape)
print("dimensions are ", firstArray.ndim)
print("Length of each element ", firstArray.itemsize)

Printing Array
[[61200   407]
 [    0     0]
 [    0     0]
 [    1     0]]
Numpy Attributes
Shape is:  (4, 2)
dimensions are  2
Length of each element  2


Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [4]:
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Exercise 3: Following is the provided numPy array. Return array of items by taking the third column from all rows

In [6]:

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 

print("Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing array of items in the third column from all rows
[33 66 99]


Exercise 4: Return array of odd rows and even columns from below numpy array

In [7]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("\n Printing array of odd rows and even columns")
newArray = sampleArray[::2, 1::2]
print(newArray)


 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


Exercise 5: Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [11]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

for num in np.nditer(resultArray, op_flags = ['readwrite']):
   num[...] = num*num
print("the square root of all elements")
print(resultArray)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]
the square root of all elements
[[ 400 1521 1089]
 [ 625  625  784]]


Python Pandas Exercise

In [15]:
import pandas as pd
df = pd.read_csv("/content/ds_salaries.csv")
df

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

Exercise 1: Clean the dataset and update the CSV file? Replace all column values which contain ?, n.a, or NaN.

In [18]:
new_data=df.dropna()
print(new_data)
df.fillna(0,inplace=True)

     Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Dat

Exercise 2: Find the most expensive car company name? Print most expensive car’s company name and price.

In [20]:
df = df [['job_title','salary']][df.salary==df['salary'].max()]
df

job_title    salary
177  Data Scientist  30400000

Exercise 3: Print All Toyota Cars details?

In [22]:
x = df.groupby('job_title')
x.get_group('Data Scientist')


job_title    salary
177  Data Scientist  30400000

Exercise 4: Count total cars per company?

In [23]:

df['job_title'].value_counts()

Data Scientist    1
Name: job_title, dtype: int64

Exercise 5: Find each company’s Higesht price car?

In [24]:
x = df.groupby('job_title')
x['job_title','salary'].max()


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  


job_title    salary
job_title                               
Data Scientist  Data Scientist  30400000