In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/ds_salaries.csv')
df

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

Pandas Exercises

1)Find the average mileage of each salaries?

In [3]:
mileageSalary = df['salary'].mean()
mileageSalary

324000.0626029654

2: Sort all salaries by location column?

In [4]:
salary = df.sort_values(by = ['salary'],  ascending=False)
salary.head()

Unnamed: 0  work_year experience_level employment_type        job_title  \
177         177       2021               MI              FT   Data Scientist   
7             7       2020               MI              FT   Data Scientist   
102         102       2021               MI              FT  BI Data Analyst   
137         137       2021               MI              FT      ML Engineer   
136         136       2021               MI              FT      ML Engineer   

       salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
177  30400000             CLP          40038                 CL           100   
7    11000000             HUF          35735                 HU            50   
102  11000000             HUF          36259                 HU            50   
137   8500000             JPY          77364                 JP            50   
136   7000000             JPY          63711                 JP            50   

    company_location company_size  
177               CL            L  
7                 HU            L  
102               US            L  
137               JP            S  
136               JP            S

3: Create two data frames using the following two
Dicts, Merge two data frames, and append the second
data frame as a new column to the first data frame.

In [6]:
from pandas.core.reshape.merge import merge
data1={'students':['khalil','mohamed'],'english':[9,10]}
data2={'students':['khalil','mohamed'],'math':[10,8]}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
df3=pd.merge(df1,df2,on='students')
df3

students  english  math
0   khalil        9    10
1  mohamed       10     8

Numpy Exercises

1: Split the array into four equal-sized sub-arrays

In [7]:
print("Creating 8X3 array")
array = np.arange(10, 34,1)
array2 = array.reshape(8,3)
subArrays = np.split(array2, 4) 
print(subArrays)

Creating 8X3 array
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


2: Sort following NumPy array
 Case 1: Sort array by the second row
 Case 2: Sort the array by the second column

In [ ]:


array = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print(array)

byRow = array[:,array[1,:].argsort()]
print("Sorting by row")
print(byRow)

print("Sorting by column")
byColumn = array[array[:,1].argsort()]
print(byColumn)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting by row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting by column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


3: Print max from axis 0 and min from axis 1 from the
following 2-D array.

In [ ]:
array = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (array)

minOfAxisOne = np.amin(array, 1) 
print('min of axis one : ')
print(minOfAxisOne)

maxOfAxisOne = np.amax(array, 0) 
print('max of axis one : ')
print(maxOfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
min of axis one : 
[34 12 53]
max of axis one : 
[82 94 73]


4: Delete the second column from a given array and
insert the following new column in its place.

In [8]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[:,1:2]=10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])